sudo: false
language: go

go:
  - 1.7
  - tip

before_install:
  - mkdir -p $GOPATH/bin
  - wget https://github.com/Masterminds/glide/releases/download/v0.12.3/glide-v0.12.3-linux-amd64.tar.gz -O /tmp/glide-v0.12.3-linux-amd64.tar.gz
  - tar -xvf /tmp/glide-v0.12.3-linux-amd64.tar.gz
  - export PATH=$PATH:$PWD/linux-amd64/

install:
  - make bundle

script:
  - make clean
  - make test
  - make bench
  - make all-build
